name: Merge Dev to Main

on:
  push:
    branches:
      - develop

jobs:
  merge-to-main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Fetch latest changes from main
      run: git fetch --all

    - name: Switch to main
      run: git checkout main

    - name: Pull latest changes from main
      run: git pull origin main

    - name: Merge dev into main
      run: git merge develop

    # - name: Push changes to main
    #   run: |
    #     git config --global user.email "actions@github.com"
    #     git config --global user.name "GitHub Actions"
    #     git push origin main
