name: deploy master to production

on:
  push:
    branches:
      - main

jobs:
  merge-to-main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH password and Deploy to Server
      run: |
          export SSHPASS="123456"
          sshpass -e ssh -o StrictHostKeyChecking=no ubuntu@65.2.81.97 'git config --global --add safe.directory /home/projects/library && cd /home/projects/library && chmod 644 .git/FETCH_HEAD && git pull origin main'
         
        
