name: deploy master to production

on:
  push:
    branches:
      - main

jobs:
  merge-to-main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        touch ~/.ssh/password
        echo "123456" > ~/.ssh/password
        chmod 600 ~/.ssh/password
        export SSHPASS=$(cat ~/.ssh/password)

    - name: Deploy to Server
      run: |
        # Add your deployment script or commands here
        sshpass -e ssh ubuntu@65.2.81.97 'cd /home/projects/library && git pull origin main'
