name: Merge Dev to Main

on:
  push:
    branches:
      - develop

jobs:
  merge-to-main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set git identity
      run: |
        git config --global user.email "rnishant2796@gmail.com"
        git config --global user.name "Nishant825"

    - name: Fetch latest changes from main
      run: git fetch --all

    - name: Switch to main
      run: git checkout main

    - name: Pull latest changes from main
      run: git pull origin main

    - name: Merge dev into main
      run: git merge develop --allow-unrelated-histories
